// Build script: embed the Zenith agent skill and the bundled SVG icon libraries
// into the binary.
//
// The skill is the canonical, hand-edited source under `assets/skill` (the
// folder tree) and `assets/plugin-commands` (slash-commands). This script walks
// those directories and generates an `include_str!`-based manifest in `OUT_DIR`,
// so the content is compiled into the binary and ships in the crates.io tarball.
//
// The SVG icon libraries under `assets/libraries/icons/<name>/` get the same
// treatment: each directory of `*.svg` files (plus its optional `library.kdl`
// manifest) becomes one entry in a generated `EMBEDDED_SVG_LIBRARIES` table.
// Generating the table here — rather than committing a derived `.zen` pack —
// keeps the vendored SVGs the single source of truth.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap_or_default());
    let skill_dir = manifest_dir.join("assets").join("skill");
    let cmd_dir = manifest_dir.join("assets").join("plugin-commands");
    let icons_dir = manifest_dir.join("assets").join("libraries").join("icons");

    rerun_if_changed(&skill_dir);
    rerun_if_changed(&cmd_dir);
    rerun_if_changed(&icons_dir);

    let skill_files = collect_files(&skill_dir);
    let cmd_files = collect_files(&cmd_dir);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap_or_default());
    let dest = out_dir.join("skill_assets.rs");
    let generated = render_manifest(&skill_files, &cmd_files);
    fs::write(&dest, generated).expect("write skill_assets.rs");

    let dest = out_dir.join("svg_libraries.rs");
    let generated = render_svg_libraries(&icons_dir);
    fs::write(&dest, generated).expect("write svg_libraries.rs");
}

/// Render the `EMBEDDED_SVG_LIBRARIES` table: one entry per `icons/<name>/`
/// directory, each holding its optional `library.kdl` manifest and every `*.svg`
/// file keyed by stem. Directories and icons are emitted in sorted order, so the
/// generated table — and everything derived from it — is deterministic.
fn render_svg_libraries(icons_dir: &Path) -> String {
    let mut dirs: Vec<PathBuf> = match fs::read_dir(icons_dir) {
        Ok(entries) => entries
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect(),
        Err(_) => Vec::new(),
    };
    dirs.sort();

    let mut s = String::new();
    s.push_str("// @generated by build.rs — do not edit.\n");
    s.push_str("/// SVG icon libraries bundled into the binary, sorted by directory name.\n");
    s.push_str("pub static EMBEDDED_SVG_LIBRARIES: &[RawSvgLibrary] = &[\n");
    for dir in &dirs {
        let Some(name) = dir.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let mut icons: BTreeMap<String, PathBuf> = BTreeMap::new();
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) != Some("svg") {
                    continue;
                }
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    icons.insert(stem.to_owned(), path.clone());
                }
            }
        }
        if icons.is_empty() {
            continue;
        }

        s.push_str("    RawSvgLibrary {\n");
        s.push_str(&format!("        dir: {name:?},\n"));
        let manifest = dir.join("library.kdl");
        if manifest.is_file() {
            s.push_str(&format!(
                "        manifest: Some(include_str!({:?})),\n",
                manifest.display().to_string()
            ));
        } else {
            s.push_str("        manifest: None,\n");
        }
        s.push_str("        icons: &[\n");
        for (stem, path) in &icons {
            s.push_str(&format!(
                "            ({:?}, include_str!({:?})),\n",
                stem,
                path.display().to_string()
            ));
        }
        s.push_str("        ],\n");
        s.push_str("    },\n");
    }
    s.push_str("];\n");
    s
}

/// Collect text files under `root`, keyed by forward-slash relative path, sorted.
fn collect_files(root: &Path) -> BTreeMap<String, PathBuf> {
    let mut out = BTreeMap::new();
    walk(root, root, &mut out);
    out
}

fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            let key = rel.to_string_lossy().replace('\\', "/");
            out.insert(key, path.clone());
        }
    }
}

fn render_manifest(skill: &BTreeMap<String, PathBuf>, cmds: &BTreeMap<String, PathBuf>) -> String {
    let mut s = String::new();
    s.push_str("// @generated by build.rs — do not edit.\n");
    s.push_str("/// Skill tree files: (relative path, contents).\n");
    s.push_str("pub static SKILL_FILES: &[(&str, &str)] = &[\n");
    for (rel, path) in skill {
        s.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            rel,
            path.display().to_string()
        ));
    }
    s.push_str("];\n\n");
    s.push_str("/// Slash-command files: (file name, contents).\n");
    s.push_str("pub static COMMAND_FILES: &[(&str, &str)] = &[\n");
    for (rel, path) in cmds {
        s.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            rel,
            path.display().to_string()
        ));
    }
    s.push_str("];\n");
    s
}

fn rerun_if_changed(path: &Path) {
    println!("cargo:rerun-if-changed={}", path.display());
}
