//! Shared fixtures for the schema drift-guard tests: a representative
//! `add_asset` op, the exhaustive op→tag map, and the canonical tag set.

use crate::op::{AddAssetMetadata, Op};
use std::collections::BTreeSet;

pub(super) fn add_asset_sample_op() -> Op {
    Op::AddAsset {
        id: "asset.logo".into(),
        kind: "image".into(),
        src: "img/logo.png".into(),
        sha256: Some("abc".into()),
        metadata: Box::new(AddAssetMetadata {
            producer_kind: Some("file-import".into()),
            producer_source: Some("assets/logo.png".into()),
            ai_prompt: Some("logo prompt".into()),
            ai_model: Some("gpt-image-1".into()),
            ai_provider: Some("openai".into()),
            ai_seed: Some(42),
            ai_generation_date: Some("2026-07-07".into()),
            ai_license: Some("project-owned".into()),
            ai_source_rights: Some("original".into()),
            ai_safety_status: Some("reviewed".into()),
            ai_reuse_policy: Some("internal".into()),
        }),
    }
}

/// Exhaustive map from an `Op` reference to its JSON tag string.
///
/// The exhaustive `match` here is the **compile-time drift guard**: when a
/// new `Op` variant is added the compiler forces this fn to be updated,
/// which in turn forces `op_names()` and `op_summary()` to be updated.
pub(super) fn op_tag(op: &Op) -> &'static str {
    match op {
        Op::SetTextAlign { .. } => "set_text_align",
        Op::MoveForward { .. } => "move_forward",
        Op::MoveBackward { .. } => "move_backward",
        Op::MoveToFront { .. } => "move_to_front",
        Op::MoveToBack { .. } => "move_to_back",
        Op::SetFill { .. } => "set_fill",
        Op::SetFillRule { .. } => "set_fill_rule",
        Op::SetStroke { .. } => "set_stroke",
        Op::SetStrokeWidth { .. } => "set_stroke_width",
        Op::SetNodeToken { .. } => "set_node_token",
        Op::SetSpanText { .. } => "set_span_text",
        Op::SetVisible { .. } => "set_visible",
        Op::SetLocked { .. } => "set_locked",
        Op::SetGeometry { .. } => "set_geometry",
        Op::NudgeGeometry { .. } => "nudge_geometry",
        Op::SetAnchor(_) => "set_anchor",
        Op::NudgeAnchorGap { .. } => "nudge_anchor_gap",
        Op::DetachAnchor { .. } => "detach_anchor",
        Op::NudgeLinePoints { .. } => "nudge_line_points",
        Op::SetPoints { .. } => "set_points",
        Op::SetPathAnchors { .. } => "set_path_anchors",
        Op::SetPathAnchorKind { .. } => "set_path_anchor_kind",
        Op::RemovePathAnchor { .. } => "remove_path_anchor",
        Op::InsertPathAnchor { .. } => "insert_path_anchor",
        Op::InsertPathAnchorAtPoint { .. } => "insert_path_anchor_at_point",
        Op::MovePathAnchor { .. } => "move_path_anchor",
        Op::MovePathHandle { .. } => "move_path_handle",
        Op::SimplifyPathAnchors { .. } => "simplify_path_anchors",
        Op::TransformPathAnchors { .. } => "transform_path_anchors",
        Op::SnapPathAnchors { .. } => "snap_path_anchors",
        Op::MakePathSymmetric { .. } => "make_path_symmetric",
        Op::PathBoolean { .. } => "path_boolean",
        Op::AddNode { .. } => "add_node",
        Op::AddPath { .. } => "add_path",
        Op::RemoveNode { .. } => "remove_node",
        Op::SetOpacity { .. } => "set_opacity",
        Op::ReplaceText { .. } => "replace_text",
        Op::DuplicateNode { .. } => "duplicate_node",
        Op::DuplicatePage { .. } => "duplicate_page",
        Op::Group { .. } => "group",
        Op::Ungroup { .. } => "ungroup",
        Op::Reparent { .. } => "reparent",
        Op::AlignNodes { .. } => "align_nodes",
        Op::SetTextOverflow { .. } => "set_text_overflow",
        Op::AddPage { .. } => "add_page",
        Op::DeletePage { .. } => "delete_page",
        Op::ReorderPages { .. } => "reorder_pages",
        Op::AddAsset { .. } => "add_asset",
        Op::SetAsset { .. } => "set_asset",
        Op::DistributeNodes { .. } => "distribute_nodes",
        Op::CreateToken { .. } => "create_token",
        Op::UpdateTokenValue { .. } => "update_token_value",
        Op::SetStyleProperty { .. } => "set_style_property",
        Op::CreateStyle { .. } => "create_style",
        Op::DeleteStyle { .. } => "delete_style",
        Op::CreateMaster { .. } => "create_master",
        Op::DeleteMaster { .. } => "delete_master",
        Op::SetPageMaster { .. } => "set_page_master",
        Op::SetTextDirection { .. } => "set_text_direction",
        Op::FindReplaceText { .. } => "find_replace_text",
        Op::SetPageSize { .. } => "set_page_size",
        Op::AlignToEdge { .. } => "align_to_edge",
        Op::CreateRecipe { .. } => "create_recipe",
        Op::UpdateRecipe { .. } => "update_recipe",
        Op::DeleteRecipe { .. } => "delete_recipe",
        Op::SetDefault { .. } => "set_default",
        Op::RemoveDefault { .. } => "remove_default",
        Op::DetachPattern { .. } => "detach_pattern",
        Op::SetLayout(_) => "set_layout",
    }
}

/// Canonical set of all op tags as derived from the exhaustive match above.
///
/// Kept in sync with `op_tag` by the assertions in the test below.
pub(super) fn all_exhaustive_tags() -> BTreeSet<&'static str> {
    BTreeSet::from([
        "set_text_align",
        "move_forward",
        "move_backward",
        "move_to_front",
        "move_to_back",
        "set_fill",
        "set_fill_rule",
        "set_stroke",
        "set_stroke_width",
        "set_node_token",
        "set_span_text",
        "set_visible",
        "set_locked",
        "set_geometry",
        "nudge_geometry",
        "set_anchor",
        "nudge_anchor_gap",
        "detach_anchor",
        "nudge_line_points",
        "set_points",
        "set_path_anchor_kind",
        "set_path_anchors",
        "remove_path_anchor",
        "insert_path_anchor",
        "insert_path_anchor_at_point",
        "make_path_symmetric",
        "move_path_anchor",
        "move_path_handle",
        "path_boolean",
        "simplify_path_anchors",
        "snap_path_anchors",
        "transform_path_anchors",
        "add_node",
        "add_path",
        "remove_node",
        "set_opacity",
        "replace_text",
        "duplicate_node",
        "duplicate_page",
        "group",
        "ungroup",
        "reparent",
        "align_nodes",
        "set_text_overflow",
        "add_page",
        "delete_page",
        "reorder_pages",
        "add_asset",
        "set_asset",
        "distribute_nodes",
        "create_token",
        "create_style",
        "update_token_value",
        "set_style_property",
        "delete_style",
        "create_master",
        "delete_master",
        "set_page_master",
        "set_text_direction",
        "find_replace_text",
        "set_page_size",
        "align_to_edge",
        "create_recipe",
        "update_recipe",
        "delete_recipe",
        "set_default",
        "remove_default",
        "detach_pattern",
        "set_layout",
    ])
}
